import { type CompilerMode, indent } from "@bot-inventor/nodes"

/**
 * The name of the function the generated module exports. It takes the Runtime
 * rather than building one, which is what keeps discord.js out of generated
 * code and lets a test run a whole Project against a fake client.
 */
export const DEFINE_BOT = "defineBot"

/**
 * Wraps the emitted Flows into an ES module. Build produces something that runs
 * itself with a token from the environment; Development Mode produces only the
 * export, because the application supplies the Runtime and the Tracing sink.
 */
export function renderModule(program: string, mode: CompilerMode): string {
  const banner = "// Generated by Bot Inventor. Do not edit by hand."
  const declaration = [
    "/** Declares this bot's Flows on the Runtime it is given. */",
    `export function ${DEFINE_BOT}(runtime) {`,
    indent(program),
    "}"
  ]

  if (mode === "development") return `${[banner, "", ...declaration].join("\n")}\n`

  const bootstrap = [
    "",
    "// The token is never stored in the Project: it comes from the environment.",
    'const botRuntime = await createDiscordRuntime({ token: process.env.DISCORD_TOKEN ?? "" })',
    `${DEFINE_BOT}(botRuntime)`,
    "await botRuntime.start()"
  ]

  return `${[
    banner,
    'import { createDiscordRuntime } from "@bot-inventor/runtime"',
    "",
    ...declaration,
    ...bootstrap
  ].join("\n")}\n`
}
