import { catalogue as defaultCatalogue, indent, type NodeCatalogue } from "@bot-inventor/nodes"
import type { Flow, Project } from "@bot-inventor/schema"

import { compileFlow } from "./compile-flow.js"

/**
 * The source of a Node Project Export, rendered without touching the disk.
 *
 * Everything here is a pure function of the Project, so the shape of what an
 * Export writes can be tested in milliseconds; `export-node-project.ts` is the
 * part that writes it and copies the Runtime in beside it.
 *
 * The format exists for a person to read. Each Flow becomes a file named after
 * the Flow, the entry point reads top to bottom, and nothing is minified or
 * bundled — a Node Project that is correct but unreadable has missed the point.
 */

/** A file an Export writes, at a path relative to the Export's folder. */
export type GeneratedFile = {
  /** Always POSIX-separated: it is joined onto the output directory when written. */
  path: string
  contents: string
}

/** Where the vendored Runtime is copied to, relative to the Export's folder. */
export const RUNTIME_DIRECTORY = "src/runtime"

/** Where the Flows are emitted, relative to the Export's folder. */
export const FLOWS_DIRECTORY = "src/flows"

/** The file `npm start` runs. */
export const ENTRY_FILE_NAME = "index.js"

/** The environment variable carrying the bot token, in every Export format. */
export const TOKEN_VARIABLE = "DISCORD_TOKEN"

export type RenderNodeProjectOptions = {
  /**
   * The dependency ranges the generated `package.json` declares. They are
   * resolved from what this build of Bot Inventor was tested against rather
   * than written down here, so an Export can never ask for a discord.js the
   * vendored Runtime has not run on.
   */
  dependencies: Readonly<Record<string, string>>
  /** Overridable so a test can render against a catalogue of its own. */
  catalogue?: NodeCatalogue
}

const BANNER = "// Generated by Bot Inventor. Do not edit by hand."

/**
 * Renders every file an Export writes itself. The vendored Runtime is not among
 * them: it is copied, not generated.
 *
 * Flows with no Trigger emit nothing and get no file, the same rule the Single
 * File follows — a Node left unwired on the Canvas leaves no trace in the Export.
 */
export function renderNodeProject(
  project: Project,
  options: RenderNodeProjectOptions
): readonly GeneratedFile[] {
  const catalogue = options.catalogue ?? defaultCatalogue
  const modules = renderFlowModules(project, catalogue)

  return [
    { path: "package.json", contents: renderPackageJson(project, options.dependencies) },
    { path: ENTRY_FILE_NAME, contents: renderEntryPoint(modules) },
    ...modules.map(module => module.file),
    { path: ".env.example", contents: renderEnvExample() },
    { path: ".gitignore", contents: renderGitignore() },
    { path: "README.md", contents: renderReadme(project, modules) }
  ]
}

/** One Flow, as the file it became and the function that file exports. */
type FlowModule = {
  flow: Flow
  file: GeneratedFile
  /** The name of the exported function, which the entry point calls. */
  functionName: string
  /** The path the entry point imports, relative to it. */
  importPath: string
}

function renderFlowModules(project: Project, catalogue: NodeCatalogue): readonly FlowModule[] {
  // Names are assigned across the whole Project rather than per Flow, because
  // two Flows the user called the same thing must not become the same file.
  const taken = new Set<string>()
  const modules: FlowModule[] = []

  for (const flow of project.flows) {
    const program = compileFlow(flow, catalogue, "build")
    if (program.length === 0) continue

    const flowSlug = uniqueSlug(flow.name.length > 0 ? flow.name : flow.id, taken)
    const functionName = `define${pascalCase(flowSlug)}`

    modules.push({
      flow,
      functionName,
      importPath: `./${FLOWS_DIRECTORY}/${flowSlug}.js`,
      file: {
        path: `${FLOWS_DIRECTORY}/${flowSlug}.js`,
        contents: renderFlowModule(flow, functionName, program)
      }
    })
  }

  return modules
}

function renderFlowModule(flow: Flow, functionName: string, program: string): string {
  return `${[
    BANNER,
    "",
    `/** The Flow "${comment(flow.name)}": everything that happens when its Trigger fires. */`,
    `export function ${functionName}(runtime) {`,
    indent(program),
    "}"
  ].join("\n")}\n`
}

/**
 * The entry point. It is deliberately the shortest file in the Export: a reader
 * opening the folder should see the whole startup — token, Flows, connect — in
 * one screen, and go to a Flow's own file for anything else.
 */
function renderEntryPoint(modules: readonly FlowModule[]): string {
  const imports = modules.map(
    module => `import { ${module.functionName} } from "${module.importPath}"`
  )

  return `${[
    BANNER,
    "",
    "// Reads .env, so the bot can be started with `npm start` and no exported secrets.",
    'import "dotenv/config"',
    `import { createDiscordRuntime } from "./${RUNTIME_DIRECTORY}/index.js"`,
    ...imports,
    "",
    "// The token is never stored in the Project: it comes from the environment.",
    `const runtime = await createDiscordRuntime({ token: process.env.${TOKEN_VARIABLE} ?? "" })`,
    "",
    ...(modules.length === 0
      ? ["// This bot has no Flow with a Trigger, so it answers nothing."]
      : modules.map(module => `${module.functionName}(runtime)`)),
    "",
    "await runtime.start()",
    'console.log("The bot is running. Press Ctrl+C to stop it.")'
  ].join("\n")}\n`
}

function renderPackageJson(
  project: Project,
  dependencies: Readonly<Record<string, string>>
): string {
  return `${JSON.stringify(
    {
      name: packageName(project.name),
      version: "1.0.0",
      private: true,
      type: "module",
      main: ENTRY_FILE_NAME,
      scripts: { start: `node ${ENTRY_FILE_NAME}` },
      dependencies
    },
    null,
    2
  )}\n`
}

function renderEnvExample(): string {
  return `${[
    "# Copy this file to .env and fill it in. Never commit .env.",
    "",
    "# Required. The bot token from the Discord Developer Portal, under Bot > Token.",
    `${TOKEN_VARIABLE}=`,
    "",
    "# Optional. Points the bot at a proxy instead of Discord itself.",
    "# Leave it unset unless you know you need it.",
    "# DISCORD_API_URL="
  ].join("\n")}\n`
}

/**
 * The format is for someone who wants their bot in version control, and the one
 * file that must never get there is the one holding the token.
 */
function renderGitignore(): string {
  return ["node_modules/", ".env", ""].join("\n")
}

function renderReadme(project: Project, modules: readonly FlowModule[]): string {
  const flows =
    modules.length === 0
      ? ["This bot has no Flow with a Trigger yet, so it starts and answers nothing."]
      : [
          "Each Flow is one file, and each file is everything that happens when that Flow's Trigger fires:",
          "",
          ...modules.map(module => `- \`${module.file.path}\` — ${comment(module.flow.name)}`)
        ]

  return `${[
    `# ${comment(project.name)}`,
    "",
    "A Discord bot built with Bot Inventor and exported as source you host yourself.",
    "",
    "## Running it",
    "",
    "You need [Node.js](https://nodejs.org) 20 or newer.",
    "",
    "1. Install the dependencies:",
    "",
    "   ```",
    "   npm install",
    "   ```",
    "",
    "2. Make a copy of `.env.example` next to it, named `.env`, and put your bot token in it.",
    "",
    `   \`${TOKEN_VARIABLE}\` is the token from the [Discord Developer Portal](https://discord.com/developers/applications), under **Bot > Token**. Keep it out of version control: \`.env\` holds it, and nothing else in this folder does.`,
    "",
    "3. Start the bot:",
    "",
    "   ```",
    "   npm start",
    "   ```",
    "",
    "   It connects to Discord and registers its slash commands. Global commands can take up to an hour to appear the first time.",
    "",
    "## What is in here",
    "",
    `- \`${ENTRY_FILE_NAME}\` — reads the token, declares the Flows, connects to Discord.`,
    `- \`${FLOWS_DIRECTORY}/\` — one file per Flow.`,
    `- \`${RUNTIME_DIRECTORY}/\` — the small library the Flows are written against. It wraps discord.js.`,
    "",
    "## The Flows",
    "",
    ...flows,
    "",
    "## Editing it",
    "",
    "This folder is yours: it needs nothing from Bot Inventor to run. Editing it by hand is fine, but Bot Inventor cannot read your changes back — exporting the Project again overwrites this folder."
  ].join("\n")}\n`
}

/** Keeps text taken from a Project from ending a comment or a Markdown line early. */
function comment(text: string): string {
  return text.replace(/\s+/g, " ").replace(/\*\//g, "*\\/").trim()
}

/**
 * A file name a person can recognise as their Flow. Anything that is not plainly
 * safe in a path on every platform is dropped rather than escaped, because the
 * name is decoration: what makes the file findable is the README listing it.
 */
function uniqueSlug(name: string, taken: Set<string>): string {
  const base = slug(name)
  let candidate = base
  let suffix = 2
  while (taken.has(candidate)) {
    candidate = `${base}-${suffix}`
    suffix += 1
  }
  taken.add(candidate)
  return candidate
}

function slug(name: string): string {
  const cleaned = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
  return cleaned.length === 0 ? "flow" : cleaned
}

function pascalCase(slugged: string): string {
  return slugged
    .split("-")
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

/** npm is stricter about names than the editor is about Project names. */
function packageName(name: string): string {
  const slugged = slug(name)
  const usable = /^[a-z0-9]/.test(slugged) ? slugged : `bot-${slugged}`
  return usable.slice(0, 214)
}
